#@data/values
---
#@overlay/match missing_ok=True
#@overlay/match-child-defaults missing_ok=True
shared:
  environment:
  - name: ENV
    value: "staging"
  - name: ENDPOINT
    value: "staging.foo.bar"